name: Deploy

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/release/viav"
        bodyFile: "changelog.md"
        token: ${{ secrets.GITHUB_TOKEN }}
    #- name: Run tests
    #  run: cargo test --verbose
